### ISSUE TITLE
Handle credit rate limit in GraphQL code

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#11]
We have the full rate limit handling setup for Rest but not for GraphQL. For the latter we just have retry for now.
We need to handle the rate limit in GraphQL too.

**Comment by Nathan-Nesbitt** [comment]
If throttled, should this re-make the call after the appropriate amount of time based on the leak? Or is there a different approach you had in mind? @hillairet 

I think there is the potential of a query running multiple times and failing because other smaller resources are dropping the pool slightly below the required amount. For example:

| Queries | Cost |
|---------|------|
| A       | 998  |
| B       | 50   |
| C       | 50   |
| D       | 50   |
| E       | 50   |

... with `n` more queries that are equal or larger than the leak.

if we had a current pool of 800, as long as new queries keep coming in, query 'A' could be looping for a long time. Can/should we assume that this is safe from this situation? (This may be unlikely in practice, but I didn't want to assume).

**Comment by hillairet** [comment]
Interesting case ... it cannot happen in Rest so indeed the current Rest approach to throttling may be too naive ...
Let's keep this issue opened till we find a smarter way to throttle.
In the meantime we can just assume that this is an unlikely edge case.
