### ISSUE TITLE
[mypy] Strange issue in mypy `0.950`

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#125]
When updating to mypy `0.950`, a new error appears when writing the following code:

```python
from spylib import OfflineTokenABC

class OfflineTokenExecuter(OfflineTokenABC):
    async def save(self):
        pass

    @classmethod
    async def load(cls, store_name: str):  # <---  error is here
        # TODO: Loader function
        pass
```

`error: Signature of "load" incompatible with supertype "OfflineTokenABC"  [override]`

**Comment by hillairet** [comment]
That is a weird one!

**Comment by ponty33** [comment]
`abstractclassmethod` has been deprecated since Python 3.3: [Doc](https://docs.python.org/3/library/abc.html#abc.abstractclassmethod)
Maybe that's why it's not supported anymore
We should change [Here](https://github.com/SatelCreative/spylib/blob/b07578611778b54c0e0068362eb8976784c73dff/spylib/admin_api.py#L254) to:
```python
    @classmethod
    @abstractmethod
    def load(cls, store_name: str):
        pass
```
Which is recommended after Python 3.3
I tested in different code, and it's not raising error

**Comment by qw-in** [comment]
@ponty33 good catch, I guess if we make the change we should be able to update no problem then
