### ISSUE TITLE
Document supported Oauth use cases and steps

### ISSUE THREAD

**Issue by qw-in** [SatelCreative/spylib#138]
1. Offline token only
2. Online token + session tokens + embedded app
3. Wacky & custom

Create flowcharts & documentation for each of these cases. From there we can work on example implementation using the current (upcoming) utility functions and make sure all of the cases are covered

**Comment by qw-in** [comment]
#93 will be revisited once this is complete

**Comment by hillairet** [comment]
Let's document clearly the steps and use these steps and their names to create clear functions handling each step.

**Comment by hillairet** [comment]
Quick reminder note:
One of the challenge the "Online token + session tokens + embedded app" use case is changing the app scopes.

**Comment by hillairet** [comment]
Maybe we don't cover the the app scope change in this issue just to prevent it from growing too much

**Comment by hillairet** [comment]
@hillairet Break it down into 4 issues:
1. General Oauth with sequence diagram
2. Offline token only
3. Online + session tokens + embedded app
4. Wacky & custom

**Comment by qw-in** [comment]
@hillairet I'm going to bow out of this one & unsubscribe 😅

**Comment by hillairet** [comment]
Ok so here is a different approach for the docs. Three pages:

1. Explanation of the OAuth in general with sequence diagram. This is to expand and clarify the Shopify documentation. It will be also referenced by the other two pages
2. HowTo of the FastAPI OAuth that shows how to get all the parts of the OAuth done using the FastAPI specific API
3. HowTo of the framework agnostic OAuth for when we call the SPyLib functions that don't rely on FastAPI. I might still use FastAPI as the framework example because it might be useful to compare the two HowTos and offer an option to mix and match for the wacky situations.

@lishanl @ponty33 Any option/feedback/comment?

**Comment by hillairet** [comment]
Ok the work has been broken down:

1. #201 
2. #202 
3. #203
