### ISSUE TITLE
Implement the necessary backend piece for Shopify's session tokens

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#16]
The [Shopify docs on the topic](https://shopify.dev/apps/auth/session-tokens/authenticate-an-embedded-app-using-session-tokens) seems pretty complete. We should implement it in SPyLib.

**Comment by hillairet** [comment]
@Nathan-Nesbitt Please look at this next.
You could save time by looking at the `shopify-python-api` repo that has [some code](https://github.com/Shopify/shopify_python_api/blob/master/shopify/session_token.py) for this though we want it async and an API more adapted to what we do (i.e. FastAPI friendly)

**Comment by Nathan-Nesbitt** [comment]
Just writing out some logic in here for later:

- App should redirect to the authentication endpoint if the online or offline token is invalid. (This will require some changes to the OAuth flow as it currently only handles the situation where the user in attempting to validate the first time. Since we don't want to have to reauthorize the app / offline token we need to handle the case where the user just wants to reauthorize the app with existing or new scopes)
-  We should be automatically checking the [app/uninstalled](https://shopify.dev/apps/auth/session-tokens/authenticate-an-embedded-app-using-session-tokens#mark-shop-records-as-uninstalled-using-the-app-uninstalled-webhook) webhook so that when the app is uninstalled from a store, we automatically remove all instances of that store from the app.
- We should be checking the app scopes within the app on each request to avoid pointless requests that won't pass. We can get the authorized scopes [here](https://shopify.dev/apps/auth/session-tokens/authenticate-an-embedded-app-using-session-tokens#handle-changes-to-access-scopes-requested-by-your-app) and store them in the database/`Application` object
- When the `OnlineToken` expires we should be redirecting back to the OAuth screen
- (Might already be done) Verifying the token signature on each request.

**Comment by Nathan-Nesbitt** [comment]
I think it might be a good idea to check that the user's permissions are never more than the app permissions (online token should have <= online token scopes). I don't think this will happen directly from Shopify, but it could save us from making a mistake when loading scopes from a DB.
