### ISSUE TITLE
The Document Version seems off

### ISSUE THREAD

**Issue by lishanl** [SatelCreative/spylib#162]
The document versioning has been deployed: https://satelcreative.github.io/spylib

**1.**  It has the option to switch between versions 0.7.0 and 0.6.0 at the moment. Should we see more versions?

**2.** Some content don't match with the version's actual content. 
For example, [0.6.0](https://github.com/SatelCreative/spylib/tree/0.6.0/spylib) doesn't have Multipass but it shows in the document. It seems to just display the content from the latest version. 
![0 6 0](https://user-images.githubusercontent.com/26753845/183727370-6b2fac7c-c718-44b7-954a-a056bdf230c8.JPG)

**3.** Some content do match.. which is good. Then how did 2 happen? 
For example, the development-contributing page:
![0 6 0_2](https://user-images.githubusercontent.com/26753845/183728420-cea1588c-4282-4d3f-82c6-93e0a3136573.JPG)
![0 7 0_2](https://user-images.githubusercontent.com/26753845/183728431-11aa0d7a-c85d-4a95-b041-d5753b0c8a02.JPG)

Can you please take a look? @ponty33 Thanks!

**Comment by ponty33** [comment]
@lishanl 
1. The document is genereate with command, so if we want anything earlier we will have to go to that specific commit and create it manually. I think it's fine to just keep the record from now on unless we really want doc for old versions
2. It's because 0.6.0 doc was generated by me by accident :sweat_smile: It's somewere inbetween 0.6.0 and 0.7.0. The solution will be the same as above, go to the specific commit for 0.6.0 and create it manually

**Comment by ponty33** [comment]
Manually fixed, if it still not reflect the change it's probably cache
I used incognito mode and it's changed
