### ISSUE TITLE
Refactor Store class

### ISSUE THREAD

**Issue by hillairet** [SatelCreative/spylib#18]
# What, Why

To handle the online token #9 we need to rethink how we are doing the whole Store class.
At the same time let's improve the API with an overall rewrite.

# How

1. StoreAPI or StoreABC (Naming is hard) abstract class with methods that need to be overloaded:
    * `save_online_token` and `save_offline_token` to be called at the end of the OAuth process to store in DB, or wherever needed/wanted
    * `load_online_token` and `load_offline_token` to be called whenever the `load` method initiates a store
2. `load` function to instantiate the Store class with an async call:
        * If argument is just store name (store subdomain) then load offline token: `store = await Store.load(storename=storename)`
        * If argument is the store name and the staff id then load online token: `store = await Store.load(storename=storename, staff_id=staff_id)`
3. Rename `shoprequest` to something `execute_rest`

**Comment by Nathan-Nesbitt** [comment]
Could we do something like the following?
```
 Application
  |-- Store[]
  |      |--  OnlineToken[]
  |      `--  OfflineToken    
  |-- Auth
```
We have an application. In this application we have an array of stores, and an authentication implementation. For each of the stores they can have an array of OnlineTokens and a single instance of an offline token. 

**Application** *(Class)*: A container for all of the stores and the authentication. This allows us to remove the instance of a store that holds a store logic that currently exists making it clearer the scope and functionality of a store. It allows us to share one object between all routes giving access directly to all store instances and authentication endpoints without having to query for information. For example, instead of having to do the following:

```python
dbstore = await DBStore.find_one_by_name(name=storename)

return Store.load(store_id=storename, name=storename, access_token=dbstore.access_token)
```
We can instead something like the following: 
```python
application.getStore(storename)
```
Which would return an instance of a store loaded in our application.

**Store** *(Class)*: A store contains the core functionality for making queries on a single store, it holds its own authentication tokens, both online (up to `n`) and offline (up to `1`). We could implement it so that a store could be created like the following:

```python
store_1 = Store(
  store_name,
  api_version,
  max_tokens,
  rate 
)
```

**Auth** *(Class)*: This handles all of the logic associated with oauth. Instead of initializing the routes separately from the original application, this combines the OAuth portion into the initialization of the application so you only have to make one call. 

```python
my_application = Application(
    app_domain,
    app_scopes,
    client_id,
    client_secret,
    shopify_handle,
    user_scopes,
    callback_path,
    install_init_path,
    [stores]
)
```

**Token** *(Abstract Class)*: This token abstract class contains most of the logic for a token, providing the functionality to create and renew a token. This should not be instantiated directly. This lets the programmer implement their own logic for how the save and load functionality for a token works (if necessary).

**OnlineToken** *(Class)*: This provides the functionality for an online token (information about user). We can set this up to be a default approach for storing an online token.

**OfflineToken** *(Class)*: This provides the functionality for the basic offline token. We can set this up to be a default approach for storing an offline token.

**Comment by hillairet** [comment]
So I'm gonna do what I should have done earlier (My bad! :sweat: ) and document clearly what I have in mind and a little why this approach. Slack is the worst to agree on design!  :expressionless: 
The code below my have errors obviously. It's for design reference.

We just need 3 classes to rewrite the current `Store` class (which handles only offline tokens). I believe we can make them all as `BaseModel` from pydantic but that might not work.

* First a `TokenABC` with all the methods and attributes shared by online and offline tokens. At this time it's best to pretty much copy paste most of the Store class, as much as possible. I put here just the two main method to more or less copy paste.
```python
class TokenABC(BaseModel, ABC):
    access_token: str
    store_name: str
    <and the other attributes>

    async def execute_rest(<stuff>):
         <code>
    async def execute_gql(<stuff>):
         <code>
```
* The `OfflineTokenABC` class which will also be an abstract class. It should pretty much be `TokenABC` in that case.
* FYI there is a way to make the return type for `load` to be the inherited class and not OfflineTokenABC. Use [Generic](https://github.com/orgs/SatelCreative/teams/python/discussions/64)
```python
class OfflineTokenABC(TokenABC):
    @abstractmethod
    async def save(self):
        pass
    @abstractmethod
    @classmethod
    async def load_token(cls, store_name: str):
         pass
```
* The `OnlineTokenABC` almost the same as above:
```python
class OnlineTokenABC(TokenABC):
    staff_id: str                         # Might as well make it a class attribute. We don't have to though ...
    @abstractmethod
    async def save(self):
        pass
    @abstractmethod
    @classmethod
    async def load_token(cls, store_name: str, staff_id: str):
         pass
```

Now in terms of usage, using the `OfflineToken` as example:
```python
class OfflineToken(OfflineTokenABC):
     async def save(self):
        <Implement saving the class to the DB>
    @classmethod
    async def load(cls, store_name: str, staff_id: str):
        <Implement loading the class from the DB and create the OfflineToken instance>

# Then they use it through out their code:
offlinetoken = await OfflineToken.load(store_name='mytshirtsstore')
await offlinetoken.execute_rest(<stuff>)
```
Between the abstract class and pydantic, it should be really hard for the user to implement an error!
We'll implement a method for [dependency injection](https://fastapi.tiangolo.com/tutorial/dependencies/) as suggested by Quinn later on.

Let me know if you have any question.
