### ISSUE TITLE
Change REST goodstatus and error codes to class variables

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#27]
Currently we accept a "goodstatus" parameter when executing rest:

https://github.com/SatelCreative/satel-spylib/blob/3bfc32f5eee8d632d85ebd5c54e37e3d9966d4a6/spylib/store.py#L120

Can we change this to be some token variable? Like

```
class Token:
  good_status: ClassVar[int] = 200
```

this would reduce the complexity of the method call and would reduce the chance someone makes a mistake.

**Comment by Nathan-Nesbitt** [comment]
I think we could even name the error codes based on the error? For example the 429 error is rate limit hit, which we comment when we use:

https://github.com/SatelCreative/satel-spylib/blob/3bfc32f5eee8d632d85ebd5c54e37e3d9966d4a6/spylib/store.py#L127

But if we created an object for the standard error codes for Shopify we could just say:

```python
if response.status_code == response_code.rate_limit_hit:
  self.tokens = 0
```

I think this would allow for a centralized location for error codes (so if they change the API it won't be hard to change this library) and would allow for easier reading?

**Comment by Nathan-Nesbitt** [comment]
This could also be applied to the `method` parameter, which should only be accepting a finite set of options:

- GET
- DELETE
- POST
- PUT

Could we instead provide a typed class or enum? As it would allow us to obfuscate away the formatting of the request and keep the code more consistent.

```python
from shopify.requests import get, post, delete, put
await store.shoprequest(method=get)
await store.shoprequest(method=post)
```

**Comment by hillairet** [comment]
One by one:
* **Goodstatus**: It has to be per call because POST returns 201 on success. However since shopify *seems* consistent with POST being 201 and the other returning 200, we could probably deduce it from the method! Then back to your suggestion to enforce the type below. We would still keep this argument to be able to overwrite the good status code from the method.
* **Status code**: Good idea, except I'd have `if response.status_code == ResponseCode.rate_limit_hit:` as an Enum class
* **Method**: Sounds good and we could have it as constant strings such that `from shopify.requests import GET, DELETE, POST, PUT`. Using the new [TypeAlias](https://docs.python.org/3/library/typing.html#typing.TypeAlias) might be good to still use a string but a typed string and these GET, DELETE, POST and PUT would be of that type, let's say "RestMethod" for example.
